server:
  port: 8080 # This is the default port anyway, but you can change it here
  #  servlet:
  #    context-path: /resource-server

security:
  jwt:
    token:
      secret-key: "fijgfjdufighuidfhguhuiojfdsqpl@usqbfdsyb"
      expire-length: 300000

